<?php 

// This file is generated by Composer
require_once 'php-github-api/vendor/autoload.php';
$client = new Client("");
$issues = $client->api('issue')->all('KnpLabs', 'php-github-api', array('state' => 'open'));
print_r($issues);